#!/usr/bin/env bash
#-*- mode: sh -*-

export PROJECT_ROOT=$(pwd)
export PATH=$PROJECT_ROOT/env:$PATH

function build() {
    if [[ "-h" == $1 || "--help" == $1 ]]; then
        echo "Usage: build"
        echo
        return
    fi

    if [ ! -f env/build ]; then
        mkdir -p env/build
    fi

    local cflags="-std=c99 -pedantic-errors -fextended-identifiers -g -x c -Wno-format-security"

    gcc $cflags -c main.c &&
        mv *.o env/build/ &&
        gcc -o gscfg env/build/*.o
}
